### ISSUE TITLE
missing header file in ros-fuerte-libg2o

### ISSUE THREAD

**Issue by ubuntuslave** [CCNYRoboticsLab/ccny_rgbd_tools#15]
We need to let people know to do an "sudo apt-get purge ros-fuerte-libg2o"  before trying to rosmake ccny_rgb_tools.

The following error appears if the official libg2o package is installed:

"
In file included from /home/carlos/ros/stacks/ccny-ros-pkg/github/ccny_rgbd_tools/ccny_rgbd/include/ccny_rgbd/mapping/keyframe_graph_solver_g2o.h:32:0,
                   from /home/carlos/ros/stacks/ccny-ros-pkg/github/ccny_rgbd_tools/ccny_rgbd/src/mapping/keyframe_graph_solver_g2o.cpp:24:
  /opt/ros/fuerte/include/g2o/solvers/cholmod/linear_solver_cholmod.h:36:21: fatal error: cholmod.h: No such file or directory
  compilation terminated.
  make[3]: **\* [CMakeFiles/ccny_rgbd_mapping.dir/src/mapping/keyframe_graph_solver_g2o.o] Error 1
  make[3]: Leaving directory `/home/carlos/ros/stacks/ccny-ros-pkg/github/ccny_rgbd_tools/ccny_rgbd/build'
  make[2]: *** [CMakeFiles/ccny_rgbd_mapping.dir/all] Error 2
  make[2]: Leaving directory`/home/carlos/ros/stacks/ccny-ros-pkg/github/ccny_rgbd_tools/ccny_rgbd/build'
"

**Comment by ubuntuslave** [comment]
It was done already on Github, but not in the ROS wiki. I added those comments to the wiki.

**Comment by ziyangli** [comment]
Nice. But what if some other pkgs need to use ros-fuerte-libg2o?
