### ISSUE TITLE
Optimization for graph-based global alignement is not working.

### ISSUE THREAD

**Issue by ashaat** [CCNYRoboticsLab/ccny_rgbd_tools#2]
Hello!

Thanks for sharing such a nice tool. vo and normal mapping working fine. But i faced a problem in optimization using g2o. it is generating graph (using generateGraphSrvCallback), but when solveGraphSrvCallback is called it is giving following error

---

Adding vertices...
Adding edges...
Optimizing...
[VO 787] Fr: 0.0 GFT[203][196]: 52.4 ICPProbModel  3.6 TOTAL 56.7
[VO 788] Fr: 0.0 GFT[208][199]: 30.9 ICPProbModel  1.7 TOTAL 32.8
[VO 789] Fr: 0.0 GFT[210][207]: 38.5 ICPProbModel  1.4 TOTAL 40.6
[VO 790] Fr: 0.5 GFT[201][198]: 26.5 ICPProbModel  1.4 TOTAL 29.0
[VO 791] Fr: 0.0 GFT[184][180]: 27.1 ICPProbModel  1.5 TOTAL 30.4

[keyframe_mapper_node-2] process has died [pid 7952, exit code -11, cmd /home/ashaat/ros_workspace/ccny_rgbd_tools/ccny_rgbd/bin/keyframe_mapper_node __name:=keyframe_mapper_node __log:=/home/ashaat/.ros/log/51ec4e02-6ed3-11e2-9c58-20689d99b934/keyframe_mapper_node-2.log].
log file: /home/ashaat/.ros/log/51ec4e02-6ed3-11e2-9c58-20689d99b934/keyframe_mapper_node-2*.log

[VO 801] Fr: 0.0 GFT[192][190]: 34.6 ICPProbModel  1.4 TOTAL 36.5
[VO 802] Fr: 0.0 GFT[204][200]: 25.9 ICPProbModel  1.5 TOTAL 27.5
[VO 803] Fr: 0.0 GFT[197][192]: 32.0 ICPProbModel  1.5 TOTAL 33.6
[VO 804] Fr: 0.0 GFT[192][187]: 28.5 ICPProbModel  1.5 TOTAL 30.3
[VO 805] Fr: 0.0 GFT[207][199]: 28.0 ICPProbModel  1.5 TOTAL 29.6
.
.
## .

It through the error- "process has died" when function, optimizer_.optimize(10) function is called. I have tested by installing g2o separately, but got same result. 

Thanks for help in advance

cheers,

ashaat

**Comment by ccny-ros-pkg** [comment]
Thank you for the ticket. I reverted to an earlier version of the class which seems to resolve the segfault issue. It has been fixed in master, groovy, and fuerte branches
