### ISSUE TITLE
Error building on Groovy

### ISSUE THREAD

**Issue by n3opl4n** [CCNYRoboticsLab/ccny_rgbd_tools#21]
I am trying to build ccny_rgbd_tools on ROS Groovy and I get one failure.
The file "apps/global_cloud_align.cpp" seems to be missing.
It is called from a CMakelist.txt under ccny_rgbd_tools/lib_rgbdtools/rgbdtools_git with the following two lines:
add_executable(global_cloud_align
  apps/global_cloud_align.cpp)

The output from build of package lib_rgbdtools is:
git clone https://github.com/ccny-ros-pkg/rgbdtools.git rgbdtools_git
Cloning into 'rgbdtools_git'...
cd rgbdtools_git && git checkout 
touch rospack_nosubdirs
mkdir -p rgbdtools_git/build
cd rgbdtools_git/build && cmake ../ -DCMAKE_INSTALL_PREFIX=/home/fotis/groovy/rosbuild_ws/ccny_rgbd_tool/lib_rgbdtools -DG2O_INCLUDE_DIRS=/home/fotis/groovy/rosbuild_ws/ccny_rgbd_tool/ccny_g2o/include -DG2O_LIBRARY_DIRS=/home/fotis/groovy/rosbuild_ws/ccny_rgbd_tool/ccny_g2o/lib -DG2O_LIBRARIES='g2o_core;g2o_stuff;g2o_solver_cholmod;g2o_solver_csparse;g2o_types_slam3d;cholmod' 
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- checking for module 'eigen3'
--   found eigen3, version 3.0.5
-- Found eigen: /usr/include/eigen3 
-- Boost version: 1.46.1
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
-- checking for module 'openni-dev'
--   found openni-dev, version 1.5.2.23~precise
-- Found openni: /usr/lib/libOpenNI.so 
-- Found libusb-1.0: /usr/include 
-- checking for module 'flann'
--   found flann, version 1.7.1
-- Found Flann: /opt/ros/groovy/lib/libflann_cpp_s.a 
-- Found qhull: /usr/lib/libqhull.so 
-- looking for PCL_COMMON
-- Found PCL_COMMON: /opt/ros/groovy/lib/libpcl_common.so 
-- looking for PCL_OCTREE
-- Found PCL_OCTREE: /opt/ros/groovy/lib/libpcl_octree.so 
-- looking for PCL_IO
-- Found PCL_IO: /opt/ros/groovy/lib/libpcl_io.so 
-- looking for PCL_KDTREE
-- Found PCL_KDTREE: /opt/ros/groovy/lib/libpcl_kdtree.so 
-- looking for PCL_SEARCH
-- Found PCL_SEARCH: /opt/ros/groovy/lib/libpcl_search.so 
-- looking for PCL_SAMPLE_CONSENSUS
-- Found PCL_SAMPLE_CONSENSUS: /opt/ros/groovy/lib/libpcl_sample_consensus.so 
-- looking for PCL_FILTERS
-- Found PCL_FILTERS: /opt/ros/groovy/lib/libpcl_filters.so 
-- looking for PCL_GEOMETRY
-- Found PCL_GEOMETRY: /opt/ros/groovy/include/pcl-1.6 
-- looking for PCL_SEGMENTATION
-- Found PCL_SEGMENTATION: /opt/ros/groovy/lib/libpcl_segmentation.so 
-- looking for PCL_FEATURES
-- Found PCL_FEATURES: /opt/ros/groovy/lib/libpcl_features.so 
-- looking for PCL_SURFACE
-- Found PCL_SURFACE: /opt/ros/groovy/lib/libpcl_surface.so 
-- looking for PCL_REGISTRATION
-- Found PCL_REGISTRATION: /opt/ros/groovy/lib/libpcl_registration.so 
-- looking for PCL_VISUALIZATION
-- Found PCL_VISUALIZATION: /opt/ros/groovy/lib/libpcl_visualization.so 
-- looking for PCL_KEYPOINTS
-- Found PCL_KEYPOINTS: /opt/ros/groovy/lib/libpcl_keypoints.so 
-- looking for PCL_TRACKING
-- Found PCL_TRACKING: /opt/ros/groovy/lib/libpcl_tracking.so 
-- Found PCL: /usr/lib/libboost_system-mt.so;/usr/lib/libboost_filesystem-mt.so;/usr/lib/libboost_thread-mt.so;pthread;/usr/lib/libboost_date_time-mt.so;/usr/lib/libboost_iostreams-mt.so;optimized;/opt/ros/groovy/lib/libpcl_common.so;debug;/opt/ros/groovy/lib/libpcl_common.so;optimized;/opt/ros/groovy/lib/libpcl_octree.so;debug;/opt/ros/groovy/lib/libpcl_octree.so;/usr/lib/libOpenNI.so;vtkCommon;vtkRendering;vtkHybrid;optimized;/opt/ros/groovy/lib/libpcl_io.so;debug;/opt/ros/groovy/lib/libpcl_io.so;optimized;/opt/ros/groovy/lib/libflann_cpp_s.a;debug;/opt/ros/groovy/lib/libflann_cpp_s-gd.a;optimized;/opt/ros/groovy/lib/libpcl_kdtree.so;debug;/opt/ros/groovy/lib/libpcl_kdtree.so;optimized;/opt/ros/groovy/lib/libpcl_search.so;debug;/opt/ros/groovy/lib/libpcl_search.so;optimized;/opt/ros/groovy/lib/libpcl_sample_consensus.so;debug;/opt/ros/groovy/lib/libpcl_sample_consensus.so;optimized;/opt/ros/groovy/lib/libpcl_filters.so;debug;/opt/ros/groovy/lib/libpcl_filters.so;optimized;/opt/ros/groovy/lib/libpcl_segmentation.so;debug;/opt/ros/groovy/lib/libpcl_segmentation.so;optimized;/opt/ros/groovy/lib/libpcl_features.so;debug;/opt/ros/groovy/lib/libpcl_features.so;optimized;/usr/lib/libqhull.so;debug;/usr/lib/libqhull.so;optimized;/opt/ros/groovy/lib/libpcl_surface.so;debug;/opt/ros/groovy/lib/libpcl_surface.so;optimized;/opt/ros/groovy/lib/libpcl_registration.so;debug;/opt/ros/groovy/lib/libpcl_registration.so;optimized;/opt/ros/groovy/lib/libpcl_visualization.so;debug;/opt/ros/groovy/lib/libpcl_visualization.so;optimized;/opt/ros/groovy/lib/libpcl_keypoints.so;debug;/opt/ros/groovy/lib/libpcl_keypoints.so;optimized;/opt/ros/groovy/lib/libpcl_tracking.so;debug;/opt/ros/groovy/lib/libpcl_tracking.so 
-- Configuring done
CMake Error at CMakeLists.txt:83 (add_executable):
  Cannot find source file:

```
apps/global_cloud_align.cpp
```

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

-- Build files have been written to: /home/fotis/groovy/rosbuild_ws/ccny_rgbd_tool/lib_rgbdtools/rgbdtools_git/build
make: **\* [rgbdtools_local] Error 1

**Comment by ccny-ros-pkg** [comment]
It should now be fixed in master. Make sure you do a clean build:

roscd lib_rgbdtools
make wipe && make

roscd ccny_rgbd
make clean && make
