### ISSUE TITLE
Fixing n_candidates_ instead of assert in keyframe_graph_detector.cpp

### ISSUE THREAD

**Issue by diogorolo** [CCNYRoboticsLab/ccny_rgbd_tools#22]
Hi,

Sometimes when you have a low amout of keyframes and you ask to generate the graph, the program exits due to:   assert(n_candidates_ <= size);

An alternative would be(@@ -349,7 +349,10 @@):

   // check for validity of n_candidates argument
   int size = match_matrix_.rows;

  if(n_candidates_ > size)
  {
      n_candidates_ = size;
  }
  assert(n_candidates_ <= size);

**Comment by ccny-ros-pkg** [comment]
Thank you for the ticket, fixed in master branch of rgbdtools

To rebuild:

roscd lib_rgbdtools
make wipe
make
