### ISSUE TITLE
Can I find your paper (Fast Visual Odometry and Mapping from RGB-D Data in ICRA 2013)?

### ISSUE THREAD

**Issue by stmoon** [CCNYRoboticsLab/ccny_rgbd_tools#24]
Hi...

I'm interested with your great job.. But I can't find any paper or something (I want to know the algorithm,... etc)

I know you submit "Fast Visual Odometry and Mapping from RGB-D Data" in ICRA 2013. Unfortunately, in IEEE,it doesn't update  this paper yet.
If possible, can I show your paper?

Thank you in advance..

Best Regards,
SungTae Moon

**Comment by jodafo** [comment]
So, this is quite old, but since it is still open:

The paper can be found via the authors mendeley profile: http://www.mendeley.com/profiles/ivan-dryanovski/
