### ISSUE TITLE
Launch fail to vo+mapping

### ISSUE THREAD

**Issue by HasithaBR** [CCNYRoboticsLab/ccny_rgbd_tools#29]
roslaunch ccny_openni_launch openni.launch publish_cloud:=true
roslaunch ccny_rgbd vo+mapping.launch

When I run above two commands I got like this error in vo+mapping launch. I tried both Fuerte & Groovy, but same result. Please tell me what could be this error? What must I do to resolve it? Thank you

core service [/rosout] found
ERROR: cannot launch node of type [ccny_rgbd/visual_odometry_node]: can't locate node [visual_odometry_node] in package [ccny_rgbd]
ERROR: cannot launch node of type [ccny_rgbd/keyframe_mapper_node]: can't locate node [keyframe_mapper_node] in package [ccny_rgbd]
No processes to monitor
shutting down processing monitor...
... shutting down processing monitor complete

**Comment by ubuntuslave** [comment]
Seems like your driver for the connect is not running. Test it first just by launching to openni driver alone. Once you see all these topics by the driver being published you can try to see the images and the point cloud then you could try running the visual odometry.

On Nov 12, 2013, at 1:16 AM, "HasithaBR" <notifications@github.com<mailto:notifications@github.com>> wrote:

roslaunch ccny_openni_launch openni.launch publish_cloud:=true
roslaunch ccny_rgbd vo+mapping.launch

When I run above two commands I got like this error in vo+mapping launch. I tried both Fuerte & Groovy, but same result. Please tell me what could be this error? What must I do to resolve it? Thank you

core service [/rosout] found
ERROR: cannot launch node of type [ccny_rgbd/visual_odometry_node]: can't locate node [visual_odometry_node] in package [ccny_rgbd]
ERROR: cannot launch node of type [ccny_rgbd/keyframe_mapper_node]: can't locate node [keyframe_mapper_node] in package [ccny_rgbd]
No processes to monitor
shutting down processing monitor...
... shutting down processing monitor complete

**Comment by HasithaBR** [comment]
HI, Thank you for the response. Now I can run above two and rviz after make ccny again. Now I have this problem..

[keyframe_mapper_node-3] process has died [pid 12569, exit code 127, cmd /opt/ros/fuerte/share/ros/ccny_rgbd_tools/ccny_rgbd/bin/keyframe_mapper_node __name:=keyframe_mapper_node __log:=/home/hasitha/.ros/log/531d29ea-4c4a-11e3-a74b-26d481bd4b43/keyframe_mapper_node-3.log].
log file: /home/hasitha/.ros/log/531d29ea-4c4a-11e3-a74b-26d481bd4b43/keyframe_mapper_node-3*.log

What can be the reason?

**Comment by HasithaBR** [comment]
HI all, sorry for the late, I don't get the error in libg2o in ROS Groovy (happy with it). I faced it on Fuerte and unable to build. I used this package for my project and it's perfect.
