### ISSUE TITLE
Compilation on ubuntu 14.04 and ROS indigo

### ISSUE THREAD

**Issue by GettingChen** [CCNYRoboticsLab/ccny_rgbd_tools#48]
I run rosmake ccny_rgbd_tools,When compiling to ccny-rgbd, the computer freezes. I restarted many times without any effect.Is it the ros version or something else? Hope someone will help me solve it.Many thanks!

**Comment by EricLYang** [comment]
we haven't maintained this for a long time. It was tested on http://wiki.ros.org/groovy.

Can you try it on ROS groovy or try attache some error message here?

**Comment by GettingChen** [comment]
Thanks to your reply.When compiling here, the computer is stuck, I can only force restart.
`
[rosmake-0] Starting >>> pcl_ros [ make ]                                       
[rosmake-0] Finished <<< pcl_ros ROS_NOBUILD in package pcl_ros
No Makefile in package pcl_ros
[rosmake-1] Finished <<< lib_rgbdtools [PASS] [ 1.05 seconds ]                  
[rosmake-1] Starting >>> ccny_rgbd [ make ]                                     
[ rosmake ] [ make ] [ ccny_rgbd: 24.4 sec ]         [ 1 Active 70/71 Complete ]
`
Can the code be changed to make it compileable under indigo？
