### ISSUE TITLE
Support for 32FC1 depth images

### ISSUE THREAD

**Issue by astaranowicz** [CCNYRoboticsLab/ccny_rgbd_tools#8]
Trying to use the PR2 in Gazebo, the simulated Kinect gives different image encoding in regards to the depth-map related topics.  The simulated Kinect uses 32FC1 instead of the normal 16UC1 which is used by the real Kinect.

**Comment by idryanov** [comment]
Now suppotrs 32FC1 images. They are converted (internally) to 16UC1. This takes about 1 to 2ms per image on my i7. Passing 16UC1 is still slightly more efficient.
